In [38]:
import torch as torch
import torch.nn as nn
from torchinfo import summary

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [39]:
features = torch.rand(10,5)

In [40]:
model = Model(features.shape[1])

In [41]:
model(features)

tensor([[0.5736],
        [0.5940],
        [0.5783],
        [0.6111],
        [0.5736],
        [0.6050],
        [0.5779],
        [0.6063],
        [0.5852],
        [0.6011]], grad_fn=<SigmoidBackward0>)

In [46]:
model.network[0].weight

Parameter containing:
tensor([[-0.1960, -0.4074,  0.0974,  0.4448,  0.0196],
        [ 0.1382,  0.1235, -0.3459,  0.1601, -0.1250],
        [-0.3643,  0.3505,  0.3220, -0.0647, -0.0486]], requires_grad=True)

In [47]:
model.network[0].bias

Parameter containing:
tensor([-0.4371, -0.0878,  0.0612], requires_grad=True)

In [48]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00